### ISSUE TITLE
How to change the direction of the horizontal bar graph

### ISSUE THREAD

**Issue by welyt** [DingWB/PyComplexHeatmap#12]
![image](https://user-images.githubusercontent.com/8581547/220139964-0e905cfe-cfed-4c1b-9320-0ed28cf6c262.png)
![image](https://user-images.githubusercontent.com/8581547/220140311-7ae3f102-f7be-4e16-921e-b07c671fffad.png)

**Comment by DingWB** [comment]
Thank for your feedback. Please remove the package and install it again. Make sure you are using the latest version.
Go to [here](https://dingwb.github.io/PyComplexHeatmap/build/html/notebooks/advanced_usage.html#4.-Annotations) for documentation about how to change the orientation of annotation.
