### ISSUE TITLE
I think you have repaired it, so I upgraded to the latest version(v1.2.7), but it ran incorrectly

### ISSUE THREAD

**Issue by welyt** [DingWB/PyComplexHeatmap#13]
![image](https://user-images.githubusercontent.com/8581547/220223494-0d40c086-af6f-4c9b-ae43-d1fda31b2db0.png)

**Comment by DingWB** [comment]
It should be fixed. Please reinstall and try again.
Please let me know whether it works or not.

**Comment by welyt** [comment]
great, it works. 👍
