### ISSUE TITLE
Your wiki page is GitHub theme dependent

### ISSUE THREAD

**Issue by RamRS** [DingWB/PyComplexHeatmap#20]
Hi,

The images you use in your wiki page seem to be GitHub theme dependent. I had to change my GitHub theme to view them properly. My default them is "Dark default". When I view [the wiki page](https://github.com/DingWB/PyComplexHeatmap/wiki/Parameters) with that theme, this is what I see:

![screenshot - dark theme](https://user-images.githubusercontent.com/4529399/228331002-80e733cf-4350-48bd-827c-0fb48f5d658f.png)

But when I switch to the "Light default" theme, I see everything properly:

![screenshot - light theme](https://i.ibb.co/FYsMfN0/image.png)

**Comment by RamRS** [comment]
Sorry about the late response. And no, it's not fixed yet - in fact, there's no change at all.

**Comment by RamRS** [comment]
Why am I unable to reopen this issue?

**Comment by DingWB** [comment]
It's reopened now.

**Comment by DingWB** [comment]
Please recheck it. Does it work for you now?

**Comment by RamRS** [comment]
The first image has a white background now for both light and dark themes. The second and third images seem to have a transparent bg. While this does not affect the second image (it still looks weird but not unintelligible), the rownames and colnames in the third heatmap disappear in the dark theme. You should also be able to enable themes and check images on your end.

**Comment by DingWB** [comment]
Thanks for your feedback. But I will not spend too much time accommodating different github themes cause it is not that important to me.
You can switch to a traditional theme to view the wiki/parameter, or you can just save the picture on your own computer for easy access.

**Comment by RamRS** [comment]
Another option is to have the images as clickable links (`<a href="image.png" target="_blank"><img src="image.png"></a>` that opens the image in a new tab and add some text stating that if the images don't render properly owing to GitHub themes, click on the image to view it in a new tab - that fixes the problem.

**Comment by DingWB** [comment]
This is a good suggestion. Could you please modify it and make a pull request?

**Comment by RamRS** [comment]
I did not know one could fork and modify the wiki, or I'd have contributed in a better manner. I'll fix the images and add links and submit a PR over the next few days.

**Comment by RamRS** [comment]
For the moment, you're welcome to look at https://github.com/RamRS/PyComplexHeatmap/wiki/Features - the image is stable across themes.

**Comment by RamRS** [comment]
I have updated the wiki pages to be theme independent. Apparently PRs cannot be created for wiki pages, so please clone https://github.com/RamRS/PyComplexHeatmap.wiki.git, set https://github.com/DingWB/PyComplexHeatmap.wiki.git as a remote and push to that remote to merge in the changes.

**Comment by DingWB** [comment]
Thank you, Ram. I have already pushed your wiki.git to https://github.com/DingWB/PyComplexHeatmap.wiki.git.
Please recheck whether it works.

**Comment by DingWB** [comment]
BTW, what do you think of this PyComplexHeatmap? Do you have any suggestions for this package?

**Comment by RamRS** [comment]
I'll check it out. I use ComplexHeatmap A LOT but I stay away from Python so any testing will need to be exclusively for the purpose of testing your package, not during regular usage.

**Comment by RamRS** [comment]
Hi, your wiki images are back to being broken after your latest commit. All it takes is to replace the transparent background with a white background on the PNG files. Maybe do that before uploading the images to github?
