### ISSUE TITLE
set heatmap title

### ISSUE THREAD

**Issue by welyt** [DingWB/PyComplexHeatmap#22]
How to set a title of heatmap？

**Comment by DingWB** [comment]
This is a good question.
Setting the title in PyComplexHeatmap is easy, just like setting the title for other python plots (using `ax.set_title`).
You need to get the main ax and call `ax.set_title`, such as `cm.ax.set_title("title")`.
You can refer to [this example](https://dingwb.github.io/PyComplexHeatmap/build/html/notebooks/composite_heatmaps.html#Composite-two-heatmaps-horizontally-for-mouse-DNA-methylation-array-dataset) (not sure whether you need to clear the cache of your browser to see the latest changes).
