### ISSUE TITLE
How to return  clustered data matrix after using ClusterMapPlotter function

### ISSUE THREAD

**Issue by Xinfeng-Yao** [DingWB/PyComplexHeatmap#23]
cm =ClusterMapPlotter(data=df_heatmap,  z_score=0)

cm.data2d will not return clustered matirx but return a matrix with original row/colunm order. So how to get a clustered matirx like using sns.clustermap.
Thanks.

**Comment by DingWB** [comment]
Please refer to [issue 2](https://github.com/DingWB/PyComplexHeatmap/issues/2).
Briefly, you can use `cm.row_order` and `cm.col_order` to get the clustered rows and columns.
I hope my answer is helpful to you.
Thanks for your feedback.
