### ISSUE TITLE
anno_simple colors are wrong

### ISSUE THREAD

**Issue by Laolga** [DingWB/PyComplexHeatmap#32]
I want to plot 22 groups on top of my heatmap with light and dark grey.
For the colors argument I'm using the following dictionary:
```
{1: '#999993',
 2: '#eeeee4',
 3: '#999993',
 4: '#eeeee4',
 5: '#999993',
 6: '#eeeee4',
 7: '#999993',
 8: '#eeeee4',
 9: '#999993',
 10: '#eeeee4',
 11: '#999993',
 12: '#eeeee4',
 13: '#999993',
 14: '#eeeee4',
 15: '#999993',
 16: '#eeeee4',
 17: '#999993',
 18: '#eeeee4',
 19: '#999993',
 20: '#eeeee4',
 21: '#999993',
 22: '#eeeee4'}
```
And then plot the heatmap like this:
```
plt.figure(figsize=(10, 5))


cols = HeatmapAnnotation(chromosome = anno_simple(cut_chroms.chromosome,add_text=True, colors = colors, text_kws ={"color": "black"} )
                         ,plot_legend = True,axis = 1,plot = False)
cm1 = ClusterMapPlotter(data=hm,row_dendrogram=True,show_rownames=False,show_colnames=False,top_annotation = cols,
                       row_cluster_metric = "euclidean",col_cluster = False,
                      row_cluster = True, label='Expression')

plt.show()
```
![image](https://github.com/DingWB/PyComplexHeatmap/assets/33780205/c4c4ed87-1eea-48c9-ae23-c7623bb7c8ab)
As you see, in the initial dictionary group 16 was supposed to be light grey (unlike 15 and 17) and you can also see that in the legend it's light grey, but in the heatmap it's dark grey. Could you please suggest what might be an issue?

**Comment by DingWB** [comment]
Could you please upload the data you used so I can debug it?

**Comment by DingWB** [comment]
Could you let me know if you solved this issue?

**Comment by tyamadat** [comment]
Hi, I have encountered the same issue in my script. Apparently this happens when the number of the annotation is >= 22. In my case, the color of the 13th and 14th annotations should be distinct, but they are both plotted in the 13th annotation color, although the legend looks normal. I am wondering if you have any idea to fix this. Thank you in advance.

**Comment by DingWB** [comment]
Could you please try to use `cmap='cmap50'` and rerun it? The default colormap, such as Set1 and Dark2, only has 10 different kinds of color; cmap50 is a custom colormap in PyComplexHeatmap.

**Comment by DingWB** [comment]
That's weird. Let me find the reason and fix it.

**Comment by DingWB** [comment]
I found the bug and fixed it. Please update to the newest version (1.5.2) and try again. @tyamadat  @Laolga

**Comment by DingWB** [comment]
Here is an example to test:
```python
colors={}

for i in range(1,23):
    c='#eeeee4' if i %2 ==0 else '#999993'
    colors['chr'+str(i)]=c
print(colors)

cut_chroms=pd.DataFrame(['chr'+str(i) for i in range(1,23)],columns=['chromosome'])
cut_chroms.chromosome=cut_chroms.chromosome.map(str)


plt.figure(figsize=(12, 5))
col_ha = HeatmapAnnotation(chromosome = anno_simple(cut_chroms.chromosome,colors = colors,add_text=True,text_kws={'rotation':90,'fontsize':8,'color':'black'}),
                         plot=True,plot_legend = True,axis = 1)
plt.show()
```

**Comment by tyamadat** [comment]
Thank you for your quick response. Here's what I get by running your example. I"ll also try to figure out what's happening. Thanks. 
![Screenshot from 2023-07-11 20-07-53](https://github.com/DingWB/PyComplexHeatmap/assets/45535406/7075d586-6951-4abf-b7d6-6101194babe8)

**Comment by tyamadat** [comment]
Thank you for your quick response. I have checked the commit for v1.5.2 (https://github.com/DingWB/PyComplexHeatmap/commit/1b6cc0abf07cc9aadcea31bf00eca79dce378b4a), but I cannot find any changes which can be related to vmax. Do you refer to v.1.5.1? Thanks again.

**Comment by DingWB** [comment]
I checked again. It works on my side. Did you upgrade to 1.5.2? Try:
```shell
pip install --upgrade PyComplexHeatmap
```
Please keep me posted.

**Comment by tyamadat** [comment]
Sorry to bother you. I checked the commit record thoroughly, and I missed some commits. Now I can plot your example correctly. I really appreciate your support, and thank you so much for developing such a great package! 

![Screenshot from 2023-07-11 21-04-41](https://github.com/DingWB/PyComplexHeatmap/assets/45535406/9f48b14a-17e4-44e6-8d07-78b357884f59)
