### ISSUE TITLE
get_cmap warning

### ISSUE THREAD

**Issue by welyt** [DingWB/PyComplexHeatmap#36]
MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap(obj)`` instead

**Comment by DingWB** [comment]
Hello, Yuting. Thank you for your valuable information. I have already updated it in the latest GitHub repository.
