### ISSUE TITLE
Proprietary Microsoft font Arial generates warnings for each label on certain systems

### ISSUE THREAD

**Issue by kenibrewer** [DingWB/PyComplexHeatmap#38]
The use of the proprietary Microsoft font Arial generates a warning for each time a label is printed out on any system that doesn't have that font installed. Choice of specific fonts (especially proprietary ones) is best left to the user. 

I would recommend only specifying the "Sans-serif" font family and then letting the user's matplotlib installation use whichever applicable font of  that type they have installed instead of specifying a specific font.

**Comment by DingWB** [comment]
Thanks for your suggestions. I have already removed the code for setting the default font family in the newest version.
