### ISSUE TITLE
Question about the function of `row_split` or `col_split`

### ISSUE THREAD

**Issue by faridrashidi** [DingWB/PyComplexHeatmap#4]
It seems the functions of `row_split` and `col_split` are a bit weird. See the example below:

```
import pandas as pd
from PyComplexHeatmap import *
data = pd.DataFrame([[0,1],
                     [1,0],
                     [0,1],
                     [1,0],
                     [0,1]])
ClusterMapPlotter(data=data, linewidth=1, row_dendrogram=True, row_cluster=True)
```

<img width="300" src="https://user-images.githubusercontent.com/2772503/215396757-49df7457-c765-4160-aa85-c05e3922048c.png">

After adding `row_split=2`, one should expect to see the first two rows in the above image separated from the rest three rows. However, it looks like this is not the case and ClusterMapPlotter returns something different.
```
import pandas as pd
from PyComplexHeatmap import *
data = pd.DataFrame([[0,1],
                     [1,0],
                     [0,1],
                     [1,0],
                     [0,1]])
ClusterMapPlotter(data=data, linewidth=1, row_dendrogram=True, row_cluster=True, row_split=2, row_split_gap=5)
```

<img width="300" src="https://user-images.githubusercontent.com/2772503/215397074-130e17e7-3cc0-47e6-9be3-9822d41427d7.png">

Do you have any opinion on this?

**Comment by DingWB** [comment]
As you requested, I just added a parameter `legend_pad` to control the space between the heatmap and the legend. You can reinstall and try it.
For the row_split, you can try different `row_cluster_method` and `row_cluster_metric`, and the result maybe different.

**Comment by faridrashidi** [comment]
Thanks! Both method and metric are set to default in the above examples, but the results are different when `row_split` is added. Does setting `row_split` to something other than None alter method and metric? If not, then the results of the above examples should remain unchanged.

**Comment by DingWB** [comment]
I see. I will figure it out tomorrow and give you feedback.

**Comment by DingWB** [comment]
I have already fixed the bug about the clustering when `row_split` or `col_split` is not equal to None. In the updated version, I changed the parameter `legend_pad` to `legend_hpad`.

**Comment by DingWB** [comment]
Did you try to replace `ha` with `horizontalalignment`?
For the rotation, please refer to
```python
row_ha = HeatmapAnnotation(label=anno_label(df_cols.Family, merge=True,rotation=45),
                           Family=anno_simple(df_cols.Family, legend=True,height=5),
                           Tissue=anno_simple(df_cols.Tissue,height=5),
                           label_side='top',
                           label_kws={'rotation':45,'rotation_mode':'anchor','color':'red'},
                           axis=0)
plt.figure(figsize=(4, 7))
cm = ClusterMapPlotter(data=df.T,left_annotation=row_ha,
                       show_rownames=False, show_colnames=True,col_names_side='top',
                       row_split=df_cols.Family, cmap='exp1', label='AUC',
                       rasterized=True, legend=True,
                       xticklabels_kws={'labelrotation':45,'labelcolor':'blue'})
plt.show()
```

**Comment by faridrashidi** [comment]
See this example:

```
import pandas as pd
from PyComplexHeatmap import *
data = pd.DataFrame([[0,1],
                     [1,0],
                     [0,1],
                     [1,0],
                     [0,1]], index=list('abcde'), columns=['column1', 'column2'])
ClusterMapPlotter(data=data, linewidth=1, row_dendrogram=True,
                  row_cluster=True, row_split=2, row_split_gap=5, show_colnames=True, show_rownames=True,
                  xticklabels_kws={'labelrotation':90,'labelcolor':'blue'})
```

<img width="300" src="https://user-images.githubusercontent.com/2772503/215654447-047427b4-f0bf-44c6-92c6-3acdaf29086a.png">

**Comment by DingWB** [comment]
Please try `'labelrotation': -90`. Or you can also try 'horizontalalignment': right, and 'lablerotation': 90.

**Comment by faridrashidi** [comment]
I get an error when using `horizontalalignment`

> ValueError: keyword horizontalalignment is not recognized; ...

```
import pandas as pd
from PyComplexHeatmap import *
data = pd.DataFrame([[0,1],
                     [1,0],
                     [0,1],
                     [1,0],
                     [0,1]], index=list('abcde'), columns=['column1', 'column2'])
ClusterMapPlotter(data=data, linewidth=1, row_dendrogram=True,
                  row_cluster=True, row_split=2, row_split_gap=5, show_colnames=True, show_rownames=True,
                  xticklabels_kws={'labelrotation':90,'labelcolor':'blue', 'horizontalalignment':'right'})
```

**Comment by DingWB** [comment]
I see. `ha` was hard coding in my script. You can only use `'labelrotation': -90` to do that.

**Comment by faridrashidi** [comment]
For ease of reading, I want the xlabels to be read from bottom to top. Using a -90 degree is backwards.

**Comment by DingWB** [comment]
But it would be complicated for a common user, they have to think about the different combinations of labelrotation and ha.

**Comment by faridrashidi** [comment]
Hmm.. I see, is there anyway to have it as a parameter but with a default value instead of being hard-coded?

**Comment by DingWB** [comment]
If you really want to do that, you can try the following code for now, and I will think about how to make it into a parameter without making it more complicated:
```python
import pandas as pd
from PyComplexHeatmap import *
data = pd.DataFrame([[0,1],
                     [1,0],
                     [0,1],
                     [1,0],
                     [0,1]], index=list('abcde'), columns=['column1', 'column2'])
plt.figure()
cm=ClusterMapPlotter(data=data, linewidth=1, row_dendrogram=True,
                  row_cluster=True, row_split=2, row_split_gap=5, show_colnames=True, show_rownames=True,
                  xticklabels_kws={'labelrotation':90,'labelcolor':'blue'})
plt.setp(cm.heatmap_axes[-1,0].get_xticklabels(), rotation_mode='anchor', ha='right')
plt.show()
```
