### ISSUE TITLE
Color center?

### ISSUE THREAD

**Issue by Benfeitas** [DingWB/PyComplexHeatmap#40]
Hi

Is there a way to center the color bar around a specific number? For instance, centering at 0, without having to Z_score or scale by rows/columns?

Thanks

**Comment by DingWB** [comment]
Similar to seaborn, you can try to add `center` and `robust` parameters in `ClusterMapPlotter,` `DotClustermapPlotter.`

**Comment by DingWB** [comment]
Did it work for you?
