### ISSUE TITLE
composite() got an unexpected keyword argument 'height_ratios'

### ISSUE THREAD

**Issue by ssun1116** [DingWB/PyComplexHeatmap#43]
Hello, thanks for developing this useful tool. I encountered while using the composite() function in PyComplexHeatmap: `TypeError: composite() got an unexpected keyword argument 'height_ratios'`.

I think this is the version issue that was recently added, but not completely updated in the package.
Could you provide an update to the PyComplexHeatmap package to be able to address this problem?

Thank you in advance!

**Comment by DingWB** [comment]
This is the developmental version only available on GitHub. Please uninstall it and reinstall it using: `pip install git+https://github.com/DingWB/PyComplexHeatmap` for now.
I will make it available on pip in the next release.
