### ISSUE TITLE
is it possible to limit colorbar vmin and vmax ? 

### ISSUE THREAD

**Issue by hfl112** [DingWB/PyComplexHeatmap#49]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I am wordering can I center the colorbar with white representing 0 values ??
plt.figure(figsize=(10, 4))
```

cm = ClusterMapPlotter(data=df_heatmap.T,
                       col_cluster=False,row_cluster=False,
                       row_split=df.Group,col_split=2,
                       col_split_gap=0.5,row_split_gap=0.8,
                       label='values',row_dendrogram=True,
                       show_rownames=False,show_colnames=True,
                       tree_kws={'row_cmap': 'Set1'},verbose=0,legend_gap=5,
                       cmap='bwr',xticklabels_kws={'labelrotation':90,'labelcolor':'black'},
                       #legend_kws={'vmin':-2,'vmax':2}
                       
                      )
#plt.savefig("example0.pdf", bbox_inches='tight')
plt.show()
```
![image](https://github.com/DingWB/PyComplexHeatmap/assets/33510929/d6758f07-8296-4c14-99cf-8d87d97c99c4)

**Comment by DingWB** [comment]
Yes. You can use `vmax`, `vmin`, and `center`, just similar to seaborn.

**Comment by hfl112** [comment]
> Yes. You can use `vmax`, `vmin`, and `center`, just similar to seaborn.

Thanks
