### ISSUE TITLE
Thick white lines appearning in clustermap when large genesets used

### ISSUE THREAD

**Issue by julie-jch** [DingWB/PyComplexHeatmap#52]
**Describe the bug**
I have a matrix of size 157 rows (genes) × 1023 columns (cells). When I create a clustermap plot, I get these thick white lines/ artifacts appearing in the image. 

![image](https://github.com/DingWB/PyComplexHeatmap/assets/90422532/01a35ce2-7353-42ef-b07f-77cb07f4015e)

**Expected behavior**

When I reduce the size of my matrix 59 rows (genes) × 1023 columns (cells), the clustermap outputs as it should.
![image](https://github.com/DingWB/PyComplexHeatmap/assets/90422532/357811a7-c088-4473-870e-99d9a87167da)

What can I do about this?

**Desktop (please complete the following information):**
 -Linux Mint 20.1
 - Chrome
 - Jupyter Notebook

**Additional context**
Plots generated following [this](https://dingwb.github.io/PyComplexHeatmap/build/html/notebooks/single_cell_methylation.html) tutorial with own data

**Comment by DingWB** [comment]
Could you please check whether there were missing values in the data of 157 rows (genes) × 1023 columns (cells)?
I think the white rows were missing values.

**Comment by julie-jch** [comment]
Thank you. The issue was caused because of rows or columns which contained all zeros across the dataframe. When the
 the z_score parameter was used, naturally the calculation failed on these rows/columns and resulted in NaNs which caused the white lines in plots.

**Comment by DingWB** [comment]
Great! Thanks for letting me know.
