### ISSUE TITLE
Missing annotation

### ISSUE THREAD

**Issue by ChuweiLin** [DingWB/PyComplexHeatmap#55]
version 1.6.1
matplotlib ver. 3.8.0
numpy ver. 1.26.1
pandas ver.  2.1.1
I ran the example code and the resulting figure only showed part of the annotation.
![output](https://github.com/DingWB/PyComplexHeatmap/assets/111815931/e48238ed-4471-4c92-b8e3-a70ec15d3648)

**Comment by DingWB** [comment]
This is weird. But matplotlib 3.8 is known to have some issues with this package.
Please try a lower version of matplotlib (such as 3.7) and try again.
At the same time, I will create the same environment and debug it.
Thanks for your feedback.

**Comment by ChuweiLin** [comment]
matplotlib 3.7 works fine. Thank you so much! It's a wonderful package.
