### ISSUE TITLE
Try to save results from ClusterMapPlotter as pdf, but the heatmap is a figure not in vector

### ISSUE THREAD

**Issue by kerenzhou062** [DingWB/PyComplexHeatmap#56]
Try to save results from ClusterMapPlotter as pdf, but the heatmap is a figure not in vector.

`plt.figure(figsize=(6, 30))
cm = ClusterMapPlotter(data=data.loc[:,df_col.index.tolist()],
                       top_annotation=col_ha,show_rownames=True,
                       row_cluster=True,col_cluster=False,
                       label='on/off',legend_gap=7,
                       cmap='Purples',rasterized=True)

plt.savefig(root + "test.pdf")
plt.show()
`

**Comment by DingWB** [comment]
Did you set
```
plt.rcParams['font.family']='sans serif'
plt.rcParams['font.sans-serif']='Arial'
plt.rcParams['pdf.fonttype']=42
```

and use 
```
plt.savefig("clustermap.pdf", bbox_inches='tight')
```
to save the figure?

If not, please do so and follow by any example on the documentation website, for example: https://dingwb.github.io/PyComplexHeatmap/build/html/notebooks/composite_heatmaps.html#Composite-two-heatmaps-horizontally-for-mouse-DNA-methylation-array-dataset

**Comment by DingWB** [comment]
Oh, I see.
Please use `rasterized=False`, then the pdf should be editable.

**Comment by DingWB** [comment]
However, when your data is enormous and set `rasterized=False`, the size of the generated pdf would be very large.

**Comment by kerenzhou062** [comment]
Thanks, it works now. Well, you always need to adjust the figures to fit different arrangements when get it published.

**Comment by DingWB** [comment]
I see. Thanks for the question.
