### ISSUE TITLE
MatplotlibDeprecationWarning

### ISSUE THREAD

**Issue by welyt** [DingWB/PyComplexHeatmap#58]
The register_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Use ``matplotlib.colormaps.register(name)`` instead.

**Comment by DingWB** [comment]
Hi, Yuting. I appreciate your reminder.
I also noticed this warning and have already added a `try` and `except` in the source code. So it won't get an error in a new release.
