### ISSUE TITLE
barplot not correct(anno 0-0.05,  should 0-0.5 like legend)

### ISSUE THREAD

**Issue by welyt** [DingWB/PyComplexHeatmap#6]
heatmap 的柱状图的范围不正确，应该是0～0.5， 而且理论上图例不应该显示0～0.5 颜色变化

![image](https://user-images.githubusercontent.com/8581547/217728308-374a4a77-8c0a-407d-a552-bae70bb0eb1a.png)
![image](https://user-images.githubusercontent.com/8581547/217729090-ce2f261e-fd53-4998-8246-dc0850d5fd42.png)

**Comment by DingWB** [comment]
Thanks for you to report the bug.
For the legend of `ctDNA_percent`, you can turn off the legend by setting `legend=False` in`anno_barplot`.
For the wrong range of the y-axis in the barplot, could you please give me an example dataset so I can reproduce your result?

**Comment by welyt** [comment]
thank you for your reply,  today I rerun the code(jupyter) , the bar range correct! 
if set the legend_witdh=5, the legend sample_type not show complete. so I set legend_width=10. any suggest?

![image](https://user-images.githubusercontent.com/8581547/218357473-8bfd88c6-950d-4f15-ac28-82869b18aaf3.png)
[sample_info_value_df.txt](https://github.com/DingWB/PyComplexHeatmap/files/10718192/sample_info_value_df.txt)
[sample_heatmap_value_df.txt](https://github.com/DingWB/PyComplexHeatmap/files/10718193/sample_heatmap_value_df.txt)

**Comment by DingWB** [comment]
OK, thanks for your feedback.
You can either increase the `legend_width` or replace 'mix_health' with a shorted name or abbreviation.
