### ISSUE TITLE
Missing annot when using composite

### ISSUE THREAD

**Issue by racng** [DingWB/PyComplexHeatmap#62]
**Describe the bug**
Missing custom annot (stars indicating statistical significance) when using clustermap.composite. Individual `ClusterMapPlotter` calls successfully displayed the heatmap annotation.

**Environment**
Python 3.11.7
PyComplexHeatmap 1.6.4
matplotlib 3.7.1

**Comment by DingWB** [comment]
Did you solve this problem, could you please give more detail information?
