### ISSUE TITLE
Cluster mitake occur in pyHeatmap

### ISSUE THREAD

**Issue by xiandxing** [DingWB/PyComplexHeatmap#67]
I just install pycomplexheatmap==1.6.5
pyComplextHeatmap used (col_split=2, row_split=3) as an clustering example in its document, yet when I add col_split to 3 or 3+, it will make mistake easily
"
cm = ClusterMapPlotter(data=df_heatmap, top_annotation=col_ha, col_split=3, row_split=6, col_split_gap=0.5,
row_split_gap=1,label='values',row_dendrogram=True, col_dendrogram=True,show_rownames=False,show_colnames=False,
tree_kws={'row_cmap': 'Dark2', 'col_cmap': 'Dark2'},cmap='Spectral_r', legend_gap=5,legend_hpad=2,legend_vpad=5)
"
ValueError: The number of observations cannot be determined on an empty distance matrix.

So this situation appears in my data too, and what's even worse, some branches are in the wrong place.
"
cm = ClusterMapPlotter(data=data, label='values', 
                       col_split=2, row_split=3,
                       # row_cluster_method="average", row_cluster_metric="correlation",
                       # col_cluster_method="average", col_cluster_metric="correlation",
                       # tree_kws={'row_cmap': 'Dark2'},
                       row_dendrogram=True, col_dendrogram=True, cmap='Spectral_r', show_rownames=True, show_colnames=True
                       )
"
<img width="965" alt="mistake_pycomplexheatmap" src="https://github.com/DingWB/PyComplexHeatmap/assets/89734894/bf822acc-5def-4b67-95b3-2bc638b44bfa">
I Hope the author could find it well and help me to solve it.

**Comment by DingWB** [comment]
Hello Kaiixn, @xiandxing
I just fixed a small bug, could you please update to the latest version (1.6.6) and try again?
There is no error in my test, see https://dingwb.github.io/PyComplexHeatmap/build/html/notebooks/advanced_usage.html#cluster_within_groups-&&-cluster_between_groups:-col_split=*,-col_split_order=%22cluster_between_groups%22,col_cluster=True

Please let me know whether it works for you or not.

**Comment by xiandxing** [comment]
I have updated my pycomplexheatmap to 1.6.6, yet there was still something wrong with my row or column cluster.
Finally it works out when I install fastcluster, according to the author, to calculate linkage instead of scipy.

THX!!!
