### ISSUE TITLE
How to remove arrows for anno_label

### ISSUE THREAD

**Issue by mtvector** [DingWB/PyComplexHeatmap#68]
I'm wondering how to remove the arrows from anno_label and just show the labels alone? I've tried changing values for the arrowprops argument and relpos but whatever I do I can't get rid of the lines. I can't find anything in the docs or the source to help but would love to be able to do this.
Thanks!

**Comment by DingWB** [comment]
Hello @mtvector ,

This is a good question. I just made a small change to the source code. 
Please install the developmental version from GitHub (`pip install git+https://github.com/DingWB/PyComplexHeatmap`).
To remove the arrow, add the following parameter to the anno_label:
```shell
arrowprops = dict(visible=False)
```

**Comment by DingWB** [comment]
I upgrade the package to 1.7.0, please install 1.7.0 and see [here](https://dingwb.github.io/PyComplexHeatmap/build/html/notebooks/advanced_usage.html#Add-selected-rows-labels) for example about how to remove arrow. In this example, the arrow in the `anno_label` of column annotation is removed using custom parameter `arrowprops`.

**Comment by mtvector** [comment]
That's fantastic, thank you for fixing this so quickly! I have to say this package is awesome and is the foundation for the main figure in my paper!

**Comment by DingWB** [comment]
I am happy to hear that. @mtvector 
I would appreciate it if you could cite the paper in your manuscript.
About how to cite, please see [here](https://github.com/DingWB/PyComplexHeatmap?tab=readme-ov-file#citation)
