### ISSUE TITLE
Boxplot orientation for `left_annotation`

### ISSUE THREAD

**Issue by Jieran-S** [DingWB/PyComplexHeatmap#70]
> **Is your feature request related to a problem? Please describe.**

When plotting left boxplot annotation, even if I set the variable as suggested in the tutorial, the boxplot annotation on the left is still oriented to the right (meaning 0 at left and 1 at right), see image below for better demonstration.

My code for the left_annotation is 
```
row_ha = HeatmapAnnotation(sample=anno_label(row_split, merge=True, rotation=0), 
                           domains=anno_simple(row_anno.domains), 
                           samples=anno_simple(row_anno.samples),
                           all_method_result=box, #anno_boxplot(results, cmap="cividis", height=20, legend=False),
                           axis=0, orientation='left')
```

And I call this annotation in `ClusterMapPlotter` by
```
cm = ClusterMapPlotter(data=results, 
top_annotation=col_ha, 
right_annotation=row_ha,
col_split = col_anno.method, 
col_cluster = False, 
row_split=row_split, 
row_cluster=False, 
col_split_gap = 1, 
...)
``` 

---

> **Describe the solution you'd like**

Checking the source code, we only call `vert=False` when we select `axis=0` and that automatically changes the boxplot into a **horizontal but right-facing** orientation. I was wondering if we can add something like
```
if orientation == "left":
     self.ax = self.ax.invert_yaxis()
```
or something similar to change the orientation of the boxplot? 

---

This is the boxplot orientation I am talking about: if the annotation is on the left, 0 should be on the right and 1 should be on the right
![Screenshot 2024-04-15 at 14 38 48](https://github.com/DingWB/PyComplexHeatmap/assets/91852421/5ca136bd-b559-4ba7-ac5e-f0a247f27a2c)

**Comment by DingWB** [comment]
What do you mean by "0 should be on the right and 1 should be on the right"?
Did you follow [this documentation](https://dingwb.github.io/PyComplexHeatmap/build/html/notebooks/advanced_usage.html#Change-orentation-to-the-left).

If you want to change the side of the ticks from left to right? you can try the parameter `label_side` (see [here](https://dingwb.github.io/PyComplexHeatmap/build/html/PyComplexHeatmap.annotations.html#PyComplexHeatmap.annotations.HeatmapAnnotation)), if you set  `label_side`  to the left, then the ticks will be put on the right and vice versa.

**Comment by DingWB** [comment]
I checked again. I didn't find any problem, could you please look into the [documentation](https://dingwb.github.io/PyComplexHeatmap/build/html/notebooks/advanced_usage.html#Change-orentation-to-the-left) and confirm?

**Comment by Jieran-S** [comment]
Hey DingWB thanks for the quick response! ☺️ Let me explain my question a bit more clearly.

Say I have a heatmap as below, with the left annotation containing the boxplot. The boxplot dataframe is essentially the heatmap dataframe, I am projecting the heatmap row-wise to generate a boxplot. 

Since the annotation is a left annotation, I would assume the boxplot to be orientated towards left, meaning the y-axis should be projecting towards left. (i.e. the minimal value of y-axis should be on the right, and the maximum y-axis value should be on the left). Whereas in this heatmap, the minimal y-axis value (0) is on the left and the max (1) is on the right, making the boxplot facing not left but right. 

![image](https://github.com/DingWB/PyComplexHeatmap/assets/91852421/49b6851b-1ea3-491f-bd87-76014974e8ca)


Here is how I coded the left annotation:

```
box = anno_boxplot(results, cmap="cividis", height=30, legend=False)
row_ha = HeatmapAnnotation(sample=anno_label(row_split, merge=True, rotation=0), 
                           domains=anno_simple(row_anno.domains), 
                           samples=anno_simple(row_anno.samples),
                           all_method_result=box, 
                           axis=0, orientation='left')
```
Could you help me check a bit which might be the problem? I tried almost everything but it just dosen't work...

**Comment by DingWB** [comment]
Hi @Jieran-S ,

Thanks for your explanation. Is there any problem if you run this [example code](https://dingwb.github.io/PyComplexHeatmap/build/html/notebooks/advanced_usage.html#Change-orentation-to-the-left)?
If not, something might be wrong with your code or data.
Could you please tell me which version you are using? If it is not the latest version, please upgrade to the newest version and try again.

If you are still facing the same issue with the latest version, please upload your data and paste your code, and I will debug it.
