### ISSUE TITLE
Missing annotations, and functionality to add line colors for row annotations

### ISSUE THREAD

**Issue by GordianArnav** [DingWB/PyComplexHeatmap#72]
**Describe the bug**
Some annotations are missing when using anno_simple(add_text = True), even after using Matplotlib 3.7.1
And how do you add linecolors for each row annotation?

![Screenshot 2024-04-25 at 12 25 43 PM](https://github.com/DingWB/PyComplexHeatmap/assets/137226936/ca35a667-ff00-4308-a42a-7d19235765dd)

**Comment by GordianArnav** [comment]
Okay I could solve the first issue by using anno_simple(add_text = True, majority = False), Can you let me know how to add line color, and line width to all of the row annotation plots?

**Comment by DingWB** [comment]
Try to add parameters to `anno_simple`, for example `linewidths=0.05,linecolor='gold'`
