### ISSUE TITLE
anno_boxplot AttributeError for colors parameter usage due to .copy() in check_colors 

### ISSUE THREAD

**Issue by rtubelleza** [DingWB/PyComplexHeatmap#74]
**Describe the bug**
- Cannot pass single colors to ```anno_boxplot``` in latest version (from 1.6.8 onwards?).
- Most likely due to ```_check_colors``` method for ```anno_boxplot``` class trying to copy the input colors string when setting self.colors
- Strings are immutable and do not have a .copy() method.
- Raises an AttributeError: 'str' object has no attribute 'copy'
- Fix: remove .copy()

**To Reproduce**
Create anno_boxplot with colors="white" or any single color

**Expected behavior**
Produce single color boxplot, with no TypeErrors

**Comment by DingWB** [comment]
Thanks for reporting this bug; it has already been fixed and pushed to GitHub.
You can install the latest version from GitHub, which will be released in the next version.
