### ISSUE TITLE
使用DotClustermapPlotter函数报错

### ISSUE THREAD

**Issue by z626093820** [DingWB/PyComplexHeatmap#85]
您好，当我使用DotClustermapPlotter函数绘制以下数据时报错FloatingPointError: NaN dissimilarity value.，但是我查看了没有NAN值，请问是为什么？谢谢
![image](https://github.com/user-attachments/assets/f2364c02-5b71-47e2-98ed-26b6d79eb3fd)

import PyComplexHeatmap
from PyComplexHeatmap import *
import matplotlib.pylab as plt
import pickle
plt.figure(figsize=(8,8))
cm = DotClustermapPlotter(data=dfbleedingckx2,x='Geneid',y='variable',value='value')
cm.ax_heatmap.grid(which='minor',color='white',linestyle='--',linewidth=1)
plt.show()

**Comment by DingWB** [comment]
如果你把row_cluster和col_cluster设置成False，还会报错吗？

**Comment by z626093820** [comment]
> 如果你把row_cluster和col_cluster设置成False，还会报错吗？你这里面虽然没有NAN，但是，对这个数据库进行pivot之后，就可能会有NaN了。比如，pivot到行：Geneid，列：variable，value：value之后的新数据库，里面应该会有NaN。你把row_cluster和col_cluster设置成False后，应该就不会报错

您好，谢谢，可以出图了。不过画出来的图为什么没有黑色边框，和事例中的不同，谢谢
![image](https://github.com/user-attachments/assets/8bbc1954-2964-4955-990a-98299e1cb52d)
例子：
![image](https://github.com/user-attachments/assets/23332894-246d-420c-8cd9-bcef6d13b471)

我的代码：
cm = DotClustermapPlotter(data=dfbleedingckx2,x='Geneid',y='variable',value='value',c='value',s='value',row_cluster=False,col_cluster=False,spines=True,show_colnames=True,show_rownames=True)
cm.ax_heatmap.grid(which='minor',color='white',linestyle='--',linewidth=1)
