### ISSUE TITLE
Category type not supported?

### ISSUE THREAD

**Issue by AaronNing** [DingWB/PyComplexHeatmap#87]
**Describe the bug**
When a column is of type category, the annotation cannot be created

**To Reproduce**
```python
df = pd.DataFrame(index=range(5))
df["ABC"] = ["A", "B", "B", "C", "C"]
pch.HeatmapAnnotation(df, plot=True)
```
This produces the annotation correctly.

```python
df = pd.DataFrame(index=range(5))
df["ABC"] = ["A", "B", "B", "C", "C"]
df["ABC"] = df["ABC"].astype("category")
pch.HeatmapAnnotation(df, plot=True)
```

This yields TypeError: Can not assign cmap for column ABC, please specify cmap

**Expected behavior**

**Screenshots**

**Additional context**
```python
print(pd.__version__)
print(mpl.__version__)
print(np.__version__)
print(pch.__version__)
```
1.5.3
3.7.1
1.22.4
1.7.6

**Comment by DingWB** [comment]
It has already been fixed, you can install the latest version from GitHub:
```
pip uninstall -y PyComplexHeatmap && pip install git+https://github.com/DingWB/PyComplexHeatmap
```
If you don't want to reinstall, you can simply specify cmap, for example: `cmap='Set'`, and there will be no error.
