### ISSUE TITLE
How to increase the distance between annotations

### ISSUE THREAD

**Issue by welyt** [DingWB/PyComplexHeatmap#9]
![image](https://user-images.githubusercontent.com/8581547/220043079-55c9aa26-a6ef-4aee-86c0-c0265214b214.png)

**Comment by DingWB** [comment]
You can add parameter `hspace` to the HeatmapAnnotation to increase the space. Please refer to [here](https://dingwb.github.io/PyComplexHeatmap/build/html/notebooks/advanced_usage.html#Change-orentation-up-to-down-and-add-extra-space).
