### ISSUE TITLE
There are two DeprecationWarnings while using PyComplexHeatmap

### ISSUE THREAD

**Issue by XuejianXiong** [DingWB/PyComplexHeatmap#92]
Hi there,

I got the following two warnings when I'm using PyComplexHeatmap today:

PyComplexHeatmap/colors.py:13: MatplotlibDeprecationWarning: The register_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Use ``matplotlib.colormaps.register(name)`` instead.
    plt.register_cmap(cmap=c)

PyComplexHeatmap/clustermap.py:765: DeprecationWarning: `product` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `prod` instead.
    self.linkage = self.calculated_linkage

I'm wondering if you would like to update PyComplexHeatmap recently. Thanks!

Best,
Xuejian

**Comment by DingWB** [comment]
The first one is a known warning, and it has been solved here:
https://github.com/DingWB/PyComplexHeatmap/blob/941d7f9fcd1de14984b87b206ad3b0fb6b808bcd/PyComplexHeatmap/colors.py#L24 

For the second warning, I will fix it soon.

**Comment by XuejianXiong** [comment]
Thank you, @DingWB!
