### ISSUE TITLE
How to center the title when combining multiple heatmaps?

### ISSUE THREAD

**Issue by muzier9** [DingWB/PyComplexHeatmap#93]
![image](https://github.com/user-attachments/assets/fd8c12fa-6d03-4812-bbe7-ae25862b5cb1)
As shown in the figure, I set the titles of two heat maps, cm1.ax.set_title("Methylation")
cm2.ax.set_title("Expression"),
However, because the second heat map has multiple annotations, the title is further away from the center of the heat map body.

I want both headings to be centered in the heat map body, and I try to use the column headings that set each heat map, xlabel='Methylation', xlabel_side='top', xlabel_kws=dict(labelpad=10), but it's not shown, but you can see the heat map on the left where labelpad Settings work, But the title doesn't show, maybe it's a bug?

**Comment by DingWB** [comment]
Hi @muzier9 ,

`cm.ax.set_title` is not a good way to set title,  you can use `xlabel, xlabel_side, and xlabel_kws` to add title.

**Comment by muzier9** [comment]
xlabel, xlabel_side, and xlabel_kws are really useful when I plot the parameter plot=True and draw a heat map separately. Here is the code I draw separately.
![image](https://github.com/user-attachments/assets/bdec9b80-94a8-442d-93f6-69f6351ad6fa)


cm1 = pch.ClusterMapPlotter(
            data=mat_meth, top_annotation=col_ha1, left_annotation=None, right_annotation=row_ha_direction,
            # show_rownames=True, row_names_side='left', yticklabels=True,
            show_colnames=True, xticklabels=True,
            col_dendrogram_kws=dict(linkage=column_linkage),
            # row_dendrogram_kws=dict(linkage=row_linkage),
            row_cluster_method='complete', row_cluster_metric='euclidean',
            row_dendrogram=True, col_dendrogram=False,
            # row_split=direction, row_split_gap=1,
            rasterized=True,vmax=1,vmin=0,center=0.5,cmap=meth_cmap,
            xlabel='Methylation', xlabel_side='top', xlabel_kws=dict(color='black', fontsize=14, labelpad=10),
            # plot=False,
            subplot_gap=0.5,
            label='methylation')
plt.show()

But when I try to draw two heat maps at the same time, as in the graph given in my previous question, the title does not display correctly. In the graph, the title "Methylation" is set by me using cm.ax.set_title. The pad is caused by my use of xlabel='Methylation', xlabel_side='top', xlabel_kws=dict(labelpad=10), You can see that xlabel, xlabel_side, and xlabel_kws don't display titles properly, but strangely, xlabel_kws=dict(labelpad=10) does.

**Comment by DingWB** [comment]
Hi @muzier9 ,

Yes, you are right. This was a bug, and I have already fixed it.
Please uninstall and install from github (`pip uninstall -y PyComplexHeatmap && pip install git+https://github.com/DingWB/PyComplexHeatmap
`) and try again, you can also see the new docu here: https://dingwb.github.io/PyComplexHeatmap/build/html/notebooks/composite_heatmaps.html

Thanks for reporting this bug.

**Comment by muzier9** [comment]
I tried it again and now it works. Thank you very much.

By the way, when two heat maps are displayed at the same time, how do I keep the body width of the two heat maps the same? You can see that the width of the heat map on the right is significantly smaller than that on the left.

**Comment by DingWB** [comment]
You can try the parameter `width_ratios` for `composite`.

**Comment by muzier9** [comment]
@DingWB Hello,

I found another bug that prompted an error when I used composite to concatenate two heatmaps with all annotations being None，like this:

    ax, legend_axes = composite(cmlist=cmlist, main=0, legend_hpad=2, legend_y=0.88, legend_gap=20, col_gap=0.1, width_ratios=[1,1.2])
TypeError: cannot unpack non-iterable NoneType object

I think composite returns a null value.

**Comment by DingWB** [comment]
Can you paste the detail error information?

**Comment by muzier9** [comment]
So here's my script, and I set all my annotations to None.

cm1 = pch.ClusterMapPlotter(
            data=mat_meth, top_annotation=None, left_annotation=None, right_annotation=None,
            # show_rownames=True, row_names_side='left', yticklabels=True,
            show_colnames=True, xticklabels=True,
            col_dendrogram_kws=dict(linkage=column_linkage),
            # row_dendrogram_kws=dict(linkage=row_linkage),
            row_cluster_method='complete', row_cluster_metric='euclidean',
            row_dendrogram=True, col_dendrogram=False,
            # row_split=direction, row_split_gap=1,
            rasterized=True,vmax=1,vmin=0,center=0.5,cmap=meth_cmap,
            xlabel='Methylation', xlabel_side='top', xlabel_kws=dict(color='black', fontsize=14, labelpad=10),
            plot=False,
            subplot_gap=0.5,
            label='methylation')

color_dict = {'hyper': 'red', 'hypo': 'blue'}

cm2 = pch.ClusterMapPlotter(
            data=mat_expr.loc[:, ordered_columns], top_annotation=None, left_annotation=None, right_annotation=None,
            show_rownames=False, show_colnames=True, xticklabels=True,
            col_dendrogram_kws=dict(linkage=column_linkage),
            row_dendrogram=False, col_dendrogram=False,
            rasterized=True, row_split_gap=0.1,vmax=1,vmin=0,center=0.5,cmap=expr_cmap,
            # row_split=direction,
            xlabel='Expression', xlabel_side='top', xlabel_kws=dict(color='black', fontsize=14, labelpad=10),
            plot=False, subplot_gap=0.5, label='expression')


cmlist = [cm1, cm2]
ax, legend_axes = composite(cmlist=cmlist, main=0, legend_hpad=2, legend_y=0.88, legend_gap=20, col_gap=0.1, width_ratios=[1,1.2])
plt.subplots_adjust(left=0.01, bottom=0.16)
plt.show()

This is the detailed error information:

Starting plotting..
Starting calculating row orders..
Reordering rows..
Starting calculating col orders..
Reordering cols..
Plotting matrix..
Collecting legends..
Starting plotting..
Starting calculating col orders..
Reordering cols..
Plotting matrix..
Collecting legends..
Traceback (most recent call last):
  File "C:\Users\Muzier\Desktop\heatmap.py", line 136, in <module>
    ax, legend_axes = composite(cmlist=cmlist, main=0, legend_hpad=2, legend_y=0.88, legend_gap=20, col_gap=0.1, width_ratios=[1,1.2])
TypeError: cannot unpack non-iterable NoneType object

**Comment by DingWB** [comment]
I need to know which line of the code got the error, but you didn't provide this information.

**Comment by muzier9** [comment]
This line:

File "C:\Users\Muzier\Desktop\heatmap.py", line 136, in
ax, legend_axes = composite(cmlist=cmlist, main=0, legend_hpad=2, legend_y=0.88, legend_gap=20, col_gap=0.1, width_ratios=[1,1.2])

**Comment by muzier9** [comment]
I realize you may want an error from an internal function? But unfortunately, this is all the error information, there is no more detailed information.

Maybe you can try setting all annotations to none in this example, and you should get the same error.
[](https://dingwb.github.io/PyComplexHeatmap/build/html/notebooks/composite_heatmaps.html)

**Comment by DingWB** [comment]
I tested, no error. But I know why you got the error.
Please remove `ax,legend_axes=` because there are no returned legend axes.

**Comment by muzier9** [comment]
I gave it a try. It works. But a frame will appear. And the legends of the two heat maps are not shown.
![image](https://github.com/user-attachments/assets/767dda42-0d78-4a38-b37d-87c0b0ccc572)

**Comment by DingWB** [comment]
Yes, you are right. This was a bug, but it has been fixed now.
You can add the `ax,legend_axes=` back, when all annotations are None, the returned legend_axes would be None.
For example:
```python
plt.figure(figsize=(6,9))
ax, legend_axes = pch.composite(cmlist=cmlist, main=0,legend_hpad=2,col_gap=0.1)
# cm1.ax.set_title("title1",y=1.03)
# cm2.ax.set_title("title2",y=1.03)
ax.set_title("Influence of SNP on DNAm reading",y=1.05,fontdict={'fontweight':'bold','color':'red'})
plt.savefig("beta_snp.pdf", bbox_inches='tight')
plt.show()
```

**Comment by muzier9** [comment]
I tried again. It's been solved. Thank you very much.
