### ISSUE TITLE
The legend panel is not fully displayed.

### ISSUE THREAD

**Issue by XuejianXiong** [DingWB/PyComplexHeatmap#95]
![heatmap](https://github.com/user-attachments/assets/5b4010b0-5d2d-4889-b5d8-849f431fdbe3)

As illustrated in the heatmap, half of the legend panel was truncated. Here is the code I used:
 
fig = plt.figure(figsize=(f_width, f_height))
heatmap = pch.ClusterMapPlotter(
            data=heatmap_data.T,
            top_annotation=col_ha,
            row_cluster=False,
            col_cluster=True,
            show_rownames=True,
            show_colnames=False,
            vmin=abund_limit[0],
            vmax=abund_limit[1],
            row_dendrogram=False,
            col_dendrogram=True,
            label="values",
            verbose=0,
            cmap=color_code,  ## To choose the build-in colormap
            rasterized=True,
            tree_kws={"row_cmap": "Dark2"},
            xlabel=f"Run ({n_r} in total)",
            ylabel=f"{data_type} ({n_p} in total)",
            xlabel_kws=dict(color="black", fontsize=12, labelpad=0),
            ylabel_kws=dict(color="black", fontsize=12, labelpad=0),
            legend_hpad=7,
            legend_gap=20,
            yticklabels=True,  ## To force display all row labels
            xticklabels_kws={"labelrotation": -45, "labelcolor": "blue"},
            yticklabels_kws={"labelsize": 8},
        )
plt.savefig(heatmap, bbox_inches="tight")

Thanks for your help!

**Comment by DingWB** [comment]
Try to adjust the parameter `legend_width.`

**Comment by XuejianXiong** [comment]
Great! It works! Thanks a lot @DingWB.

Another thing is how to get rid of the outline frame around the heatmap? Thank you!

**Comment by DingWB** [comment]
If you run any example code on the documentation website, is there an outline frame? If yes, then you need to upgrade the latest version of there must be something wrong with your code.
