### ISSUE TITLE
Installation failure with Python 3.12

### ISSUE THREAD

**Issue by wwang-chcn** [DingWB/PyComplexHeatmap#96]
**Describe the bug**
Installation failure with Python 3.12 using `pip install PyComplexHeatmap`

The dependency package fastcluster does not support Python 3.12 or newer and has not been maintained for 2 years. (https://github.com/fastcluster/fastcluster/issues/92)
Would you like to remove it and switch to other clustering method?

**Comment by DingWB** [comment]
OK, I will remove it from the default requirements.

**Comment by DingWB** [comment]
It has already been removed. Can you reinstall it from Github and test it?

**Comment by wwang-chcn** [comment]
It works, thank you so much.

**Comment by DingWB** [comment]
I just released a new version. Can you help me test this new version (1.7.9)?

**Comment by wwang-chcn** [comment]
It works. Good job!
